//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelrezervasyon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_RezervasyonEntities : DbContext
    {
        public Db_RezervasyonEntities()
            : base("name=Db_RezervasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Reservasyon> Tbl_Reservasyon { get; set; }
        public virtual DbSet<Tbl_Rezervation> Tbl_Rezervation { get; set; }
    }
}
