//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelrezervasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Reservasyon
    {
        public int RezervasyonId { get; set; }
        public string Odatürü { get; set; }
        public Nullable<short> Katno { get; set; }
        public Nullable<short> Odano { get; set; }
        public Nullable<short> Fiyat { get; set; }
    }
}
