//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelrezervasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Rezervation
    {
        public int RezervationId { get; set; }
        public Nullable<int> RezervasyonId { get; set; }
        public string TcKimlik { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<System.DateTime> AlmaTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<int> Ucret { get; set; }
    }
}
